[Matrix] remove deprecated PVR_STREAM_PROPERTY_INPUTSTREAMADDON / Cleanups
palinek/pvr.sledovanitv.cz pull request #53
Opened 2020-03-29 22:09 UTC by AlwinEsch

Commit 1:
--------------
Thought to make this to request on Kodi:
https://github.com/xbmc/xbmc/commit/a6aac07fd16f8f20389e760ddc26c5949af77f33
and remove this deprecated part.

Can you also do a test, it should normally work, but to make sure.

Commit 2:
--------------
To correct Markdown show of the links and use https

Commit 3:
--------------
To set Debian code to current standard on Kodi addons

Commit 4:
--------------
Set the language identfication strings in addon.xml to new standard

Commit 5:
--------------
Add gitignore to prevent not wanted parts

2020-03-29 22:22 UTC, AlwinEsch commented
Please wait with merge, there comes also another part on API!

2020-03-30 04:38 UTC, palinek requested changes

2020-03-30 04:38 UTC, palinek commented on .gitignore
> +# build artifacts
Please, don't add `.gitignore` into git at project level. Use it locally (not under version control) in your clone, if you need it.

I, for one, really want to know if there is a mess in my project tree.

2020-04-24 16:53 UTC, AlwinEsch commented
The request in Kodi is in, then also this can in now :smile:

2020-04-27 09:36 UTC, merged